import re

html_content = """
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office"><head> <meta name="x-apple-disable-message-reformatting" /> <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> <meta name="format-detection" content="telephone=no, date=no, address=no, email=no, url=no" /> <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;
user-scalable=no;" /> <title>Internshala Trainings</title> <!--[if gte mso 9]> <xml> <o:OfficeDocumentSettings> <o:AllowPNG/> <o:PixelsPerInch> 96 </o:PixelsPerInch> </o:OfficeDocumentSettings> </xml> <![endif]--> <style type="text/css"> #outlook a { padding: 0; } body { width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; margin: 0; padding: 0; } .ExternalClass { width: 100%; } .ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div { line-height: 100%; } img { outline: none; text-decoration: none;
-ms-interpolation-mode: bicubic; } a img { border: none; } table td { border-collapse: collapse; } table, tr, td { box-sizing: border-box; border-spacing: 0 !important; mso-table-lspace: 0px !important; mso-table-rspace: 0pt !important; mso-line-height-rule: exactly !important; } /* THEME STYLE */ </style></head><body style="margin: 0; padding: 0; min-width: 100%; text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background-color: #FFFFFF; box-sizing: border-box;"> <div style="display:none; overflow:hidden; color:#FFFFFF; opacity:0;">Internshala Student Partner Program</div> <table
role="presentation" width="642px" cellspacing="0" cellpadding="0" bgcolor="#FFF" style="margin: 0 auto; padding: 0; width: 642px; min-width: 642px; border: 1px solid #DDD; border-radius: 8px; background-color: #FFF; box-sizing: border-box; overflow: hidden;"> <thead> <tr> <td height="72px" align="center"> <a href="https://lnk.updates.internshala.com/vtrack?clientid=142167&ul=
BAFSBVJSCgtPBh0ACQEFCQhQU1d3QlJeBV8EUkdQVF1LU1FBHFBZGFQABlAGBQNVAXJAVVoEWlJSQVlfDRYHUkAaDVoa&ml=BABcBlQeCUQAAlMHCEw=&sl=d0gnSDMxRWt+Yh1eV1seTEkBAhFSQx1dCkcAS1pLUVUJVxtXXVRLVA==&pp=
ThYifTQxbWd9dyx3GwoSalgIFgBbEk4=&fl=XUAQRBVYFhdaRREcUF5EXEsLEA1WXFIaB1wIFg==&ext=dXRtX3NvdXJjZT1JU1AzOCZ1dG1fbWVkaXVtPUlTUDM4R1JBRFNNQ1AmZmlyc3RfbmFtZT1bRklSU1RfTkFNRV0="  target="_blank" style="margin: 0; padding: 0; display: block; text-decoration: none !important; outline: none !important;"> <img width="144px"
src="https://internshala.com//static/images/mail/new/internshala_logo.png" alt="Internshala" style="margin: auto; padding: 0; display: block;"> <!-- TAGLINE --> </a> </td> </tr> </thead> <tbody width="100%" cellspacing="0" cellpadding="0" border="0" bgcolor="#FFFFFF"> <tr> <td align="center"> <a href="https://lnk.updates.internshala.com/vtrack?clientid=142167&ul=
BAFSBVJSCgtPBh0ACQEFCQhQU1d3QlJeBV8EUkdQVF1LU1FBHFBZGFQABlAGBQNVAXJAVVoEWlJSQVlfDRYHUkAaDVoa&ml=BABcBlQeCUQAAlMHCEw=&sl=d0gnSDMxRWt+Yh1eV1seTEkBAhFSQx1dCkcAS1pLUVUJVxtXXVRLVA==&pp=
ThYifTQxbWd9dyx3GwoSalgIFgBbEk4=&fl=XUAQRBVYFhdaRREcUF5EXEsLEA1WXFIaB1wIFg==&ext=dXRtX3NvdXJjZT1JU1AzOCZ1dG1fbWVkaXVtPUlTUDM4R1JBRFNNQ1AmZmlyc3RfbmFtZT1bRklSU1RfTkFNRV0="  target="_blank" style="display: block;text-decoration: none;"> <table style="margin:0 auto;padding:0;width:100%;background-repeat:no-repeat;background-size:100% 100%;" cellspacing="0" cellpadding="0"
border="0"background="https://trainings.internshala.com/uploads/emailers/2023-03-13/ISP34FullDBMailer/Dedicated_emailer_3.png" "bgcolor="#ffffff"> <tr> <td height="24px" ></td> </tr> <tr> <td style="height:100%;vertical-align:baseline;" > <p style="margin:0;padding:0;font-family:Arial;font-size:14px;font-weight:500;line-height:20px;letter-spacing:0em;text-align:left;color:#00489A;" > <span style="margin:0;padding:0 0 0 24px;font-family:Arial;">Hi Samuel</span> </p> </td> </tr> <tr> <td height="1px" ></td> </tr> <tr> <td style="height:100%;vertical-align:baseline;" > <p
style="margin:0;padding:0;font-family:Arial;font-size:28px;font-weight:800;line-height:36px;letter-spacing:0em;text-align:left;color:#00489A;" > <span style="margin:0;padding:0 0 0 24px;font-family:Arial;">Be the face of Internshala</span> </p> </td> </tr> <tr> <td height="4px" ></td> </tr> <tr> <td style="height:100%;vertical-align:baseline;" > <p style="margin:0;padding:0;font-family:Arial;font-size:18px;font-weight:500;line-height:24px;letter-spacing:0em;text-align:left;color:#00489A;" > <span style="margin:0;padding:0 0 0 24px;font-family:Arial;">from the comfort of your home</span> </p>
</td> </tr> <tr> <td height="8px" ></td> </tr> <tr> <td> <div style="margin:0 0 0 24px;width:43%;border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:#00489A;" ></div> </td> </tr> <tr> <td height="8px" ></td> </tr> <tr> <td style="height:100%;vertical-align:baseline;" > <p style="margin:0;padding:0;font-family:Arial;font-size:16px;font-weight:700;line-height:20px;letter-spacing:0em;text-align:left;color:#00489A;" > <span style="margin:0;padding:0 0 0 24px;font-family:Arial;">Join India's #1 Student Partner Program</span> </p> </td> </tr> <tr> <td height="152px" ></td> </tr>
</table> </a> </td> </tr> <tr> <td style="height:100%;vertical-align:baseline;"> <p style="margin:0;padding:30px 24px 0 24px;font-family:Arial;font-size:15px;font-weight:500;line-height:25px;letter-spacing:0em;text-align:left;color:#212121;"> Hey Samuel - As a graduate student, you can <span style="margin:0;font-family:Arial;font-weight:bold;">EARN</span> huge side-income by joining the <span style="margin:0;font-family:Arial;font-weight:bold;">Internshala Student Partner</span> program where you'll also <span style="margin:0;font-family:Arial;font-weight:bold;">GAIN </span> job-ready
skills like <span style="margin:0;font-family:Arial;font-style:italic;">leadership, communication & networking!</span> </p> </td> </tr> <tr> <td style="height:100%;vertical-align:baseline;"> <p style="margin:0;padding:12px 24px 0 24px;font-family:Arial;font-size:15px;font-weight:500;line-height:25px;letter-spacing:0em;text-align:left;color:#212121;"> <span style="margin:0;font-family:Arial;font-weight:bold;"><span style="margin:0;font-family:Arial;font-style:italic;">Rewards</span></span> - Win MEGA giveaways such as an <span style="margin:0;font-family:Arial;font-weight:bold;color:red;"><span
style="margin:0;font-family:Arial;font-size:15px;">iPhone 13</span></span> , <span style="margin:0;font-family:Arial;text-decoration:underline;">BoAt SoundBar,</span> <span style="margin:0;font-family:Arial;font-style:italic;">Noise Smart Eyewear, Free Internshala Trainings</span> and more. </p> </td> </tr> <tr> <td style="height:100%;vertical-align:baseline;"> <p style="margin:0;padding:12px 24px 0 24px;font-family:Arial;font-size:15px;font-weight:500;line-height:25px;letter-spacing:0em;text-align:left;color:#212121;"> <span style="margin:0;font-family:Arial;font-weight:bold;"><span
style="margin:0;font-family:Arial;font-style:italic;">What's more</span></span> - <span style="margin:0;font-family:Arial;text-decoration:underline;">5+ Masterclasses & 15+ exciting contests</span> that come with cash rewards worth <span style="margin:0;font-family:Arial;font-weight:bold;color:red;">INR 7 Lacs+</span> </p> </td> </tr> <tr> <td style="height:100%;vertical-align:baseline;"> <p style="margin:0;padding:12px 24px 0 24px;font-family:Arial;font-size:15px;font-weight:500;line-height:25px;letter-spacing:0em;text-align:left;color:#212121;"> <span
style="margin:0;font-family:Arial;font-weight:bold;"><span style="margin:0;font-family:Arial;font-style:italic;">Eligibility</span></span> - Any student from any degree, stream, and year of study can apply </p> </td> </tr> <tr> <td style="height:100%;vertical-align:baseline;"> <p style="margin:0;padding:12px 24px 0 24px;font-family:Arial;font-size:15px;font-weight:400;line-height:25px;letter-spacing:0em;text-align:left;color:#212121;"> <span style="margin:0;font-family:Arial;font-weight:bold;"><span style="margin:0;font-family:Arial;font-style:italic;">Deadline</span></span> - <span
style="margin:0;font-family:Arial;font-style:italic;text-decoration:underline;">11th October '23</span>. Hurry up, click <a href="https://lnk.updates.internshala.com/vtrack?clientid=142167&ul=
BAFSBVJSCgtPBh0ACQEFCQhQU1d3QlJeBV8EUkdQVF1LU1FBHFBZGFQABlAGBQNVAXJAVVoEWlJSQVlfDRYHUkAaDVoa&ml=BABcBlQeCUQAAlMHCEw=&sl=d0gnSDMxRWt+Yh1eV1seTEkBAhFSQx1dCkcAS1pLUVUJVxtXXVRLVA==&pp=
ThYifTQxbWd9dyx3GwoSalgIFgBbEk4=&fl=XUAQRBVYFhdaRREcUF5EXEsLEA1WXFIaB1wIFg==&ext=dXRtX3NvdXJjZT1JU1AzOCZ1dG1fbWVkaXVtPUlTUDM4R1JBRFNNQ1AmZmlyc3RfbmFtZT1bRklSU1RfTkFNRV0="  ; target='_blank' ; style="margin:0;font-family:Arial;font-weight:bold;">here</a> or on the button below to apply! </p> </td> </tr> <tr> <td style="height:100%;vertical-align:baseline;" align="center"> <a href="https://lnk.updates.internshala.com/vtrack?clientid=142167&ul=
BAFSBVJSCgtPBh0ACQEFCQhQU1d3QlJeBV8EUkdQVF1LU1FBHFBZGFQABlAGBQNVAXJAVVoEWlJSQVlfDRYHUkAaDVoa&ml=BABcBlQeCUQAAlMHCEw=&sl=d0gnSDMxRWt+Yh1eV1seTEkBAhFSQx1dCkcAS1pLUVUJVxtXXVRLVA==&pp=
ThYifTQxbWd9dyx3GwoSalgIFgBbEk4=&fl=XUAQRBVYFhdaRREcUF5EXEsLEA1WXFIaB1wIFg==&ext=dXRtX3NvdXJjZT1JU1AzOCZ1dG1fbWVkaXVtPUlTUDM4R1JBRFNNQ1AmZmlyc3RfbmFtZT1bRklSU1RfTkFNRV0="  target="_blank" style="margin: 0 auto; padding 0; display: block;
text-decoration: none !important; text-align: center;"> <p style="margin:18px auto;padding:18px 25px;display:inline-block;border:0;border-radius:5px;background-color:#00489A;font-family:Arial;font-size:18px;font-weight:700;line-height:10px;letter-spacing:0em;text-align:center;color:#FFFFFF;">APPLY NOW</p> </a> </td> </tr> </tbody> <tfoot> <tr> <td height="118px" align="center" style="vertical-align: top;"> <div style="margin: auto; padding: 0; width: 608px; min-width: 608px; border-top: 1px solid #DDD;"></div> <p style="margin: 0; padding: 16px 16px 0 16px; font-family: Arial; font-size: 14px;
font-weight: 400; line-height: 22px; letter-spacing: 0em; text-align: center; color: #666;">Internshala (Scholiverse Educare Pvt. Ltd.)</p> <p style="margin: 0; padding: 0 16px 0 16px; font-family: Arial; font-size: 14px; font-weight: 400; line-height: 22px; letter-spacing: 0em; text-align: center; color: #666;">B-610, Unitech Business Zone Golf Course Extension Road, Sector 50, Gurugram</p> <p style="margin: 0; padding: 16px; font-family: Arial; font-size: 14px; font-weight: 400; line-height: 22px; letter-spacing: 0em; text-align: center; color: #666;">Not keen on career commitments?
Unsubscribe <a href="https://lnk.updates.internshala.com/vtrack?clientid=142167&ul=
BAFSBVJSCgtPBh0ACQEFCQhQU1d3QlJeBV8EUkdQVF1LU1FBHFBZGFQABlAGBQNVAXJAVVoEWlJSQVlfDRYHUkAaDVoa&ml=BABcBlQeCUQAAlMHC0w=&sl=d0gxSDMxRWt+Yh1eV1seTEkBAhFSQx1dCkcAS1pLUVUJVxtXXVRLVA==&pp=0&fl=XUAQRFxNFlRdXU9HSVRRTVwWTQxZRFZGCkANWFhZF1cKWxpdXE1SFghDXwRaVVUAVh0=&ext=cD1zbXVuc3ViJm1pZD0xNDgyMiZ1aWQ9W1VOSVFJRF0="  style="color: #008BDC; text-decoration: none !important;" target="_blank" xt="SPONECLICKOPTOUT">here</a> to break up with us.</p> </td> </tr> </tfoot> </table><br/><div></div><img border="0" src="https://lnk.updates.internshala.com/vtrack?clientid=142167&ul=     
BAFSBVJSCgtPBh0ACQEFCQhQU1d3QlJeBV8EUkdQVF1LU1FBHFBZGFQABlAGBQNVAXJAVVoEWlJSQVlfDRYHUkAaDVoa&ml=BABcBlQeCUQDSg==&sl=d0grSDMxRWt+Yh1eV1seTEkBAhFSQx1dCkcAS1pLUVUJVxtXXVRLVA==&c=142167" ></body></html>
"""

# Remove HTML tags using regular expression
text_only = re.sub(r'<[^>]+>', '', html_content)

# Print the text content
print(text_only)